# DOCS https://github.com/crate-ci/typos/blob/master/docs/reference.md
#───────────────────────────────────────────────────────────────────────────────

# ignore these words
[default.extend-words]
caf = "caf" # .caf extension is not a typo
