# DOCS https://github.com/aome510/spotify-player/blob/master/docs/config.md
#───────────────────────────────────────────────────────────────────────────────

default_device = "Wohnzimmer Echo"

# only works when the TUI is open. Using the shell commands via the
# Karabiner config instead, so the media keys always work.
enable_media_control = false

#───────────────────────────────────────────────────────────────────────────────

# ENABLE SPOTIFY CONNECT 
# https://github.com/aome510/spotify-player#spotify-connect
# Set up new client, with `localhost:8080` as redirect URI: https://developer.spotify.com/dashboard/

# client-id needs to be saved with `echo -n` to avoid trailing new line https://github.com/aome510/spotify-player/issues/537#issuecomment-2571601930
[client_id_command]
command = "cat"  # does not support `$HOME`
args = ["/Users/chrisgrieser/Library/Mobile Documents/com~apple~CloudDocs/Dotfolder/private dotfiles/spotify_client_id.txt"]
