# DOCS https://github.com/martinvonz/jj/blob/main/docs/config.md#configuration
#───────────────────────────────────────────────────────────────────────────────

[user]
name = "Chris Grieser"
email = "73286100+chrisgrieser@users.noreply.github.com"
