#!/usr/bin/env zsh
# INFO post-merge is triggered after a pull
#───────────────────────────────────────────────────────────────────────────────

# Delete empty folders (use `.gitkeep` to keep them)
# excluding espanso folder, because espanso recreates it & posts notification for that
find . -type d -empty -not -path "./espanso/match/packages" -delete

# Update Counter in Sketchybar
export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH
sketchybar --trigger repo-files-update
