#!/usr/bin/env zsh
# vim: filetype=bash

# Update Counter in Sketchybar
export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH
sketchybar --trigger repo-files-update

echo "hello from post-merge"
