#!/usr/bin/env zsh
# vim: filetype=sh
# INFO post-update is triggered after a commit (there is no post-push hook)

sleep 5 # wait till push is likely done
export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH
sketchybar --trigger repo-files-update
