#!/usr/bin/env zsh
# vim: filetype=sh
# INFO post-update is triggered after a push

# Update Counter in Sketchybar
sleep 1
export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH
sketchybar --trigger repo-files-update
echo "foobar"
