#!/usr/bin/env zsh
# vim: filetype=sh
# INFO post-merge is triggered after a pull
#───────────────────────────────────────────────────────────────────────────────

# Delete empty folders (use `.gitkeep` to keep them)
# excluding espanso folder, because espanso recreates it & posts notification for that
find . -type d -empty -not -path "./espanso/match/packages" -delete
