#!/usr/bin/env zsh
# vim: filetype=bash

# CONFIG
max_file_size_mb=10

#───────────────────────────────────────────────────────────────────────────────

# safeguard against accidental pushing of large files
large_files=$(find . -not -path "**/.git/**" -size +${max_file_size_mb}M)
if [[ -n "$large_files" ]]; then
	echo "Large file(s) found. Aborting commit."
	echo "$large_files" | sed 's/^/- /'
	exit 1
fi

echo "Pre-Commit passed."
