set quiet := true

reload:
    #!/usr/bin/osascript
    tell application "System Events"
        if not ((name of processes) contains "ghostty") then
            tell application "Ghostty" to launch
            delay 0.1
        end if
        tell process "ghostty"
            set frontmost to true
            click menu item "Reload Configuration" of menu "Ghostty" of menu bar 1
        end tell
    end tell
    return "" # to silence return

update-alfred-terminal:
    #!/usr/bin/env zsh
    content=$(printf "%s" "$(cat ./alfred-ghostty-opener.applescript | sed 's/"/\\"/g')")
    /usr/libexec/PlistBuddy -c "Set :custom '$content'" ../Alfred.alfredpreferences/preferences/features/terminal/prefs.plist
    killall "Alfred Preferences" &> /dev/null
    open "alfredpreferences://navigateto/features>terminal"
