set quiet := true

reload:
    #!/usr/bin/osascript
    tell application "System Events"
        if ((name of processes) contains "wezterm-gui") then
            tell process "wezterm-gui"
                set frontmost to true
                click menu item "Reload configuration" of menu "WezTerm" of menu bar 1
            end tell
        else
            tell application "WezTerm" to activate
            tell application "WezTerm" to activate
        end if
    end tell
    return "" # to silence return

update-alfred-terminal:
    #!/usr/bin/env zsh
    content=$(printf "%s" "$(cat ./alfred-wezterm-opener.applescript | sed 's/"/\\"/g')")
    /usr/libexec/PlistBuddy -c "Set :custom '$content'" ../Alfred.alfredpreferences/preferences/features/terminal/prefs.plist
    killall "Alfred Preferences" &> /dev/null
    open "alfredpreferences://navigateto/features>terminal"

open-wezterm-types-repo:
    open "https://github.com/DrKJeff16/wezterm-types"

# streaming
update-types:
    #!/usr/bin/env zsh
    rm -rf "/tmp/wezterm-types"
    rm -rf "./types"
    git clone --depth=1 "https://github.com/DrKJeff16/wezterm-types" "/tmp/wezterm-types"
    mv -f "/tmp/wezterm-types/lua/wezterm/types" "./"
    echo "Updated."
