# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/refs/heads/main/schema/markdownlint-config-schema-strict.json
# DOCS https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md
#───────────────────────────────────────────────────────────────────────────────

# MODIFIED SETTINGS
blanks-around-headings: { lines_below: 0 } # rule of proximity
ul-style: { style: sublist }
ol-prefix: { style: ordered }
line-length: { tables: false, code_blocks: false }

#──DISABLED─────────────────────────────────────────────────────────────────────
ul-indent: false # not compatible with using tabs
no-hard-tabs: false # taken care of by editorconfig
blanks-around-lists: false # space waster
first-line-heading: false # e.g., ignore-comments
no-emphasis-as-heading: false # sometimes useful
