set quiet := true

#───────────────────────────────────────────────────────────────────────────────

reload-surfingkeys:
    open -a "Brave Browser"
    sleep 0.1
    osascript -e 'tell application "Brave Browser" to tell active tab of front window to reload'

