set quiet := true

reload-adblock-rules:
    #!/usr/bin/env zsh
    git add "personal-rules.adblock" &&
        git commit --no-verify --message "chore: update adblock rules" &&
        git push &&
        open "brave://settings/shields/filters" # filters need to be updated manually

open-shields-filters:
    open "brave://settings/shields/filters"
