--------------------------------------------------------------------------------
-- INFO if abbreviations are not working, probably something has been mapped to
-- `<Space>` in insert mode
-----------------------------------------------------------------------------------

local spellfixes = {
	THe = "The",
	repalce = "replace",
	ahve = "have",
	awiat = "await",
	brwoser = "browser",
	cant = "can't",
	choer = "chore",
	chroe = "chore",
	cleitn = "client",
	curosr = "cursor",
	defualt = "default",
	doesnt = "doesn't",
	doestn = "doesn't",
	dont = "don't",
	dwon = "down",
	esle = "else",
	fales = "false",
	fiel = "file",
	flase = "false",
	fo = "of",
	fodler = "folder",
	hwo = "how",
	ignroe = "ignore",
	keybaord = "keyboard",
	lien = "line",
	markdwon = "markdown",
	mcuh = "much",
	mroe = "more",
	msot = "most",
	nromal = "normal",
	nto = "not",
	ntoe = "note",
	oepn = "open",
	onyl = "only",
	ot = "to",
	remtoe = "remote",
	reponse = "response",
	retrun = "return",
	retunr = "return",
	seperate = "separate",
	seperator = "separator",
	seperators = "separators",
	shwo = "show",
	sicne = "since",
	supress = "suppress",
	surppress = "suppress",
	surpress = "suppress",
	teh = "the",
	tempalte = "template",
	ti = "it",
	tiem = "item",
	treu = "true",
	ture = "true",
	verison = "version",
	woudl = "would",
}

for wrong, correct in pairs(spellfixes) do
	vim.keymap.set("ia", wrong, correct)
end
