name: $0

on:
  push:
    branches: [main]
    paths: [README.md]
  workflow_dispatch:

permissions:
  contents: write

#───────────────────────────────────────────────────────────────────────────────

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          echo "Hello, world!"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bot: PLACEHOLDER"
