# https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#configuration
#───────────────────────────────────────────────────────────────────────────────

use_nerdfont=true
shuffle=true
notify=true

# https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#notification-formatting
[notification_format]
title = "%title"
body = "%artists"

# https://github.com/hrkfdn/ncspot/blob/main/doc/users.md#custom-keybindings
[keybindings]
Space = "playpause"
