# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
# DOCS https://espanso.org/docs/configuration/app-specific-configurations/#advanced-use-cases-for-filter_title
#───────────────────────────────────────────────────────────────────────────────

filter_class: com.runningwithcrayons.Alfred-Preferences

extra_includes:
  - "../match/_alfred.yml"
  - "../match/_applescript.yml"
