# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
#───────────────────────────────────────────────────────────────────────────────

# DOCS https://espanso.org/docs/configuration/app-specific-configurations/#advanced-use-cases-for-filter_title
# only activates code snippets when a file of the right language is open

filter_title: \.applescript|scpt$|^Untitled

extra_includes:
  - "../match/_applescript.yml"
  - "../match/_alfred.yml"
