# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
#───────────────────────────────────────────────────────────────────────────────
# DOCS https://espanso.org/docs/configuration/app-specific-configurations/

filter_class: com.brave.Browser

extra_includes:
  - ../match/_emoji-reacts.yml
  - ../match/_mail.yml

