# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
#───────────────────────────────────────────────────────────────────────────────

# https://espanso.org/docs/configuration/app-specific-configurations/
filter_class: "com.hnc.Discord"

extra_includes:
  - "../match/_discord.yml"
  - "../match/_emoji-reacts.yml"
