# yaml-language-server: $schema=../schemas/espanso-appconfig-schema.json
#───────────────────────────────────────────────────────────────────────────────

# https://espanso.org/docs/configuration/app-specific-configurations/
filter_class: "com.hnc.Discord"

extra_includes:
  - "../match/_discord.yml"
