# https://espanso.org/docs/configuration/app-specific-configurations/
filter_class: "com.hnc.Discord"

extra_excludes:
  - "../emoji-colon-autosuggestion.yml"

extra_includes:
  - "../match/_discord.yml"
