# yaml-language-server: $schema=https://raw.githubusercontent.com/ajmarkow/espanso-schema-json/master/schemas/Espanso_Config_File_Schema.json
#───────────────────────────────────────────────────────────────────────────────

# DOCS https://espanso.org/docs/configuration/app-specific-configurations/#advanced-use-cases-for-filter_title
# disabling emojis, since `::` is needlessly triggered by toggling hidden files
# on and off

filter_exec: Finder

extra_excludes:
  - "../match/emojis-symbols.yml"
