# https://espanso.org/docs/configuration/app-specific-configurations/#advanced-use-cases-for-filter_title
# ------------------------------------------------------------------------------
# disabling emojis, since `::` is needlessly triggered by toggling hidden files
# on and off

filter_exec: Finder

extra_excludes:
  - "../match/emojis-symbols.yml"
