# deactivate emojis on these *websites*, since they have their own emoji suggester
# filter works based on window title
# - GitHub: new issues
# - GitHub: comment on existing issues
# - GitHub: editing markdown files
filter_title: ^New Issue|Issue|md at main

extra_excludes:
  - "../match/emoji-colon-autosuggestion.yml"
