# deactivate emojis on these *websites*, since they have their own emoji suggester
# filter works based on window title
# - GitHub: new issues
# - GitHub: comment on existing issues
# - Discord: Website (also for when app is not recognized)
filter_title: ^New Issue|Issue|Discord$ #

extra_excludes:
  - "../match/emoji-colon-autosuggestion.yml"
