# deactivate emojis on these *websites*, since they have their own emoji suggester
# filter works based on window title
# - GitHub: new issues
# - GitHub: comment on existing issues
# - GitHub: editing markdown files
# - Discord: fallback here to ensure Discord is recognized
filter_title: ^New Issue|Issue|md at main|Discord$

extra_excludes:
  - "../match/emoji-colon-autosuggestion.yml"
