# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
#───────────────────────────────────────────────────────────────────────────────

# Disable in Obsidian, since it conflicts too often with various things from vim
# mode. In Obsidian, capitalization are handled by the "Auto Correct Capitals
# Misspellings" plugin.
filter_class: md.obsidian

extra_excludes:
  - ../match/capitalization-autofix.yml
