# yaml-language-server: $schema=https://raw.githubusercontent.com/ajmarkow/espanso-schema-json/master/schemas/Espanso_Config_File_Schema.json
#───────────────────────────────────────────────────────────────────────────────

# disable in Obsidian, since it conflicts too often with various things from vim mode
filter_class: md.obsidian

extra_excludes:
  - "../match/capital-misspellings.yml"
