# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
#───────────────────────────────────────────────────────────────────────────────
# DOCS https://espanso.org/docs/configuration/app-specific-configurations/

filter_class: "com.tinyspeck.slackmacgap"

extra_includes:
  - "../match/_emoji-reacts.yml"
