# yaml-language-server: $schema=../schemas/espanso-appconfig-schema.json
#───────────────────────────────────────────────────────────────────────────────

filter_exec: Tot

extra_includes:
  - "../match/_tot.yml"
