# https://espanso.org/docs/configuration/app-specific-configurations/#advanced-use-cases-for-filter_title
#───────────────────────────────────────────────────────────────────────────────

filter_exec: Tot

extra_includes:
  - "../match/_tot.yml"
