# yaml-language-server: $schema=https://raw.githubusercontent.com/ajmarkow/espanso-schema-json/master/schemas/Espanso_Config_File_Schema.json
#───────────────────────────────────────────────────────────────────────────────

filter_exec: WezTerm

extra_excludes:
  - "../match/emojis-symbols.yml"
