# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
#───────────────────────────────────────────────────────────────────────────────

filter_exec: WezTerm

extra_excludes:
  - "../match/emojis-symbols.yml"
