set quiet := true

format:
    bibtex-tidy --tab --curly --no-align --no-wrap --drop-all-caps --enclosing-braces --numeric --trailing-commas --duplicates --sort-fields --remove-empty-fields --omit=month,issn,abstract main-bibliography.bib
