# using my own package config PENDING https://github.com/mason-org/mason-registry/pull/7957
---
name: stylua
description: An opinionated Lua code formatter.
homepage: https://github.com/JohnnyMorganz/StyLua
licenses:
  - MPL-2.0
languages:
  - Lua
  - Luau
categories:
  - Formatter

source:
  id: pkg:github/johnnymorganz/stylua@v2.0.2
  asset:
    - target: darwin_arm64
      file: stylua-macos-aarch64.zip
      bin: stylua
    - target: darwin_x64
      file: stylua-macos-x86_64.zip
      bin: stylua
    - target: linux_x64_gnu
      file: stylua-linux-x86_64.zip
      bin: stylua
    - target: linux_arm64_gnu
      file: stylua-linux-aarch64.zip
      bin: stylua
    - target: linux_x64
      file: stylua-linux-x86_64-musl.zip
      bin: stylua
    - target: win_x64
      file: stylua-windows-x86_64.zip
      bin: stylua.exe

bin:
  stylua: "{{source.asset.bin}}"
