set quiet

reload:
    # alternatively, use `sketchybar --hotload` for constant reloading when developing
    sketchybar --reload

docs:
    open "https://felixkratz.github.io/SketchyBar/config/bar"

inspect:
    open "https://felixkratz.github.io/SketchyBar/config/querying"

restart:
    brew services restart sketchybar
