set quiet := true

#───────────────────────────────────────────────────────────────────────────────

reload:
    sketchybar --reload

docs:
    open "https://felixkratz.github.io/SketchyBar/config/bar"

restart:
    brew services restart sketchybar

inspect-macos-menubar:
    sketchybar --query default_menu_items | jq --raw-output ".[]"

how-to-inspect-items:
    open "https://felixkratz.github.io/SketchyBar/config/querying"

