# alternatively, use `sketchybar --hotload`
reload:
    sketchybar --reload

# used for aliases
@list_menubar_items:
    sketchybar --query default_menu_items | sed '1d;$d' | cut -d'"' -f2

@docs:
    open "https://felixkratz.github.io/SketchyBar/config/bar"

restart:
    brew services restart sketchybar
