#!/usr/bin/env bash

# does not work
sketchybar \
	--default popup.drawing=true \
	--add item foo left --set foo label="bar" 

# works
# sketchybar \
# 	--default popup.drawing=true \
# 	--add item foo left --set foo label="bar" \
# 	--add item baz left --set baz label="nek"


