#!/usr/bin/env bash

#───────────────────────────────────────────────────────────────────────────────
# ENSURE STATS.APP IS RUNNING

i=0
while ! pgrep -xq "Stats"; do
	open -a "Stats"
	sleep 2
	i=$((i + 1))
	if [[ $i -gt 20 ]]; then
		osascript -e 'display notification "⚠️ Sketchybar cannot be loaded" with title "Stats does not start"'
		return 1
	fi
done

i=0
while true; do
	stats=$(sketchybar --query default_menu_items | grep --max-count=1 "Combined" | cut -d\" -f2)
	[[ -n "$stats" ]] && break
	sleep 2
	i=$((i + 1))
	if [[ $i -gt 20 ]]; then
		osascript -e 'display notification "⚠️ Sketchybar cannot be loaded" with title "Stats Combined Module not found"'
		return 1
	fi
done

#───────────────────────────────────────────────────────────────────────────────
# CONFIG

PLUGIN_DIR="$(dirname "$0")" # plugins in same folder as this rc file

if defaults read -g AppleInterfaceStyle | grep -q "Dark"; then
	BG_COLOR="0xff333333"
	FONT_COLOR="0xffffffff"
else
	BG_COLOR="0xffcdcdcd"
	FONT_COLOR="0xff000000"
fi

# HACK using popup for second row. the popup only refers to the clock item to
# anchor it to the leftmost item, it actually has nothing to do with the clock
# other method (requiring running multiple instances): https://felixkratz.github.io/SketchyBar/config/Tricks#multiple-bars
first_row="left"
second_row="popup.clock"

stats_width=250
scutil --get ComputerName | grep -q "Mother" && stats_width=225

# INFO
# use `sketchybar --hotload` to auto-reload config when building stuff

#───────────────────────────────────────────────────────────────────────────────
# SKETCHYBAR CALL

# one big call to speed up reloading https://felixkratz.github.io/SketchyBar/config/bar
sketchybar \
	--bar \
	height="60" position="top" display="all" \
	padding_left=0 padding_right=0 color="$BG_COLOR" \
	\
	--default \
	updates="when_shown" drawing="on" align="left" \
	icon.font="JetBrainsMonoNL Nerd Font:Bold:16" icon.color="$FONT_COLOR" \
	label.font="Lucida Grande:Regular:16.5" label.color="$FONT_COLOR" \
	icon.padding_left=2 icon.padding_right=1 \
	label.padding_left=2 label.padding_right=10 \
	popup.drawing=true popup.horizontal=true popup.topmost=false \
	popup.y_offset="-35" y_offset="18" \
	\
	--add item clock $first_row \
	--set clock update_freq=1 \
	script="$PLUGIN_DIR/clock.sh" \
	background.padding_left=5 \
	\
	--add item weather $first_row \
	--set weather update_freq=900 \
	script="$PLUGIN_DIR/weather.sh" \
	icon.y_offset=-1 \
	\
	--add item github_notif $first_row \
	--set github_notif update_freq=900 \
	script="$PLUGIN_DIR/github_notifications.sh" \
	--add event update-github-notifications \
	--subscribe github_notif update-github-notifications \
	--subscribe github_notif system_work \
	\
	--add item tot $first_row \
	--set tot script="$PLUGIN_DIR/tot-count.sh" \
	--add event update-tot-count \
	--subscribe tot update-tot-count \
	--subscribe tot system_woke \
	\
	--add alias "$stats" $second_row \
	--set "$stats" width="$stats_width" \
	\
	--add item sync-indicator $second_row \
	--set sync-indicator update_freq=300 \
	script="$PLUGIN_DIR/git-sync-bar-icon.sh" \
	--add event repo-files-update \
	--subscribe sync-indicator repo-files-update \
	--subscribe sync-indicator system_woke \
	\
	--add item package-updates $second_row \
	--set package-updates update_freq=43200 \
	script="$PLUGIN_DIR/homebrew-update-tracker.sh" \
	--add event homebrew-update \
	--subscribe package-updates homebrew-update \
	\
	--update

# INFO
# - `--update` needs to run at the end of config and should not be run in an item script
# - `repo-files-update` gets triggered via Hammerspoon after sync events
# - clock and alias items needs the fixed-width to fix whitespace of the item next (Stats)
# - not using builtin clock, to be able to customize font etc.
