#!/usr/bin/env bash
#───────────────────────────────────────────────────────────────────────────────
# INFO: After app update, needs to be re-granted screen recording permissions
#───────────────────────────────────────────────────────────────────────────────

i=0
# ensure Stats.app is running
while ! pgrep "Stats"; do
	open -a "Stats"
	sleep 2
	i=$((i + 1))
	[[ $i -gt 30 ]] && exit 1
done

# ensure Stats.app items are all loaded (mostly relevant after system startup)
i=0
menu_items=$(sketchybar --query default_menu_items)
while [[ ! "$menu_items" =~ Stats ]]; do
	sleep 3
	menu_items=$(sketchybar --query default_menu_items)
	i=$((i + 1))
	[[ $i -gt 20 ]] && exit 1
done

# globs are necessary, since the exact name of the menubar item changes a bit
# depending on installation whether mac is M1 or not
network_bar_item=$(echo "$menu_items" | grep -Ei "Stats.*network.*" | head -n1 | cut -d\" -f2)
cpu_bar_item=$(echo "$menu_items" | grep -Ei "Stats.*cpu" | head -n1 | cut -d\" -f2)
gpu_bar_item=$(echo "$menu_items" | grep -Ei "Stats.*gpu" | head -n1 | cut -d\" -f2)
ram_bar_item=$(echo "$menu_items" | grep -Ei "Stats.*ram" | head -n1 | cut -d\" -f2)

if [[ -z "$ram_bar_item" || -z "$cpu_bar_item" || -z "$gpu_bar_item" || -z "$network_bar_item" ]]; then
	osascript -e 'display notification "⚠️ Sketchybar cannot be loaded" with title "not all Stats items are visible"'
	exit 1
fi

#───────────────────────────────────────────────────────────────────────────────

if defaults read -g AppleInterfaceStyle | grep -iq "Dark"; then
	BG_COLOR="0xff333333"
	FONT_COLOR="0xffffffff"
else
	BG_COLOR="0xffcdcdcd"
	FONT_COLOR="0xff000000"
fi

# HACK using popup for second row. the popup only refers to the clock item to anchor it to the leftmost item,
# it actually has nothing to do with the clock
first_row="left"
second_row="popup.clock"

POPUP_Y_OFFSET=-35
HEIGHT=60                    # extra height for second row & to cover the holes at the corner where the wallpaper shines through
ITEM_Y_OFFSET=18             # needs to be adjusted for Height
PLUGIN_DIR="$(dirname "$0")" # plugins in same folder as this rc file

#───────────────────────────────────────────────────────────────────────────────

# one big call to speed up reloading https://felixkratz.github.io/SketchyBar/config/bar
sketchybar \
	--bar \
	height="$HEIGHT" position=top display=all \
	padding_left=0 padding_right=0 color="$BG_COLOR" \
	--default \
	updates=when_shown drawing=on align=left \
	icon.font="JetBrainsMonoNL Nerd Font:Bold:16" icon.color="$FONT_COLOR" \
	label.font="Lucida Grande:Regular:16.5" label.color="$FONT_COLOR" \
	icon.padding_left=2 icon.padding_right=1 \
	label.padding_left=2 label.padding_right=10 \
	popup.drawing=true popup.horizontal=true popup.topmost=false \
	popup.y_offset="$POPUP_Y_OFFSET" y_offset="$ITEM_Y_OFFSET" \
	\
	--add item clock $first_row \
	--set clock update_freq=1 \
	script="$PLUGIN_DIR/clock.sh" \
	background.padding_left=5 \
	\
	--add item covid-stats $first_row \
	--set covid-stats update_freq=43200 \
	script="$PLUGIN_DIR/covid-stats.sh" \
	\
	--add item weather $first_row \
	--set weather update_freq=1800 \
	script="$PLUGIN_DIR/weather.sh" \
	icon.y_offset=-1 \
	\
	--add item drafts $first_row \
	script="$PLUGIN_DIR/drafts-counter.sh" \
	--add event drafts-counter-update \
	--subscribe drafts drafts-counter-update \
	--subscribe drafts system_woke \
	\
	--add alias "$ram_bar_item" $second_row \
	--set "$ram_bar_item" width=38 \
	--add alias "$cpu_bar_item" $second_row \
	--set "$cpu_bar_item" width=60 \
	--add alias "$gpu_bar_item" $second_row \
	--set "$gpu_bar_item" width=55 \
	--add alias "$network_bar_item" $second_row \
	--set "$network_bar_item" width=95 \
	\
	--add item sync-indicator $second_row \
	--set sync-indicator update_freq=300 \
	script="$PLUGIN_DIR/git-sync-bar-icon.sh" \
	--add event repo-files-update \
	--subscribe sync-indicator repo-files-update \
	--subscribe sync-indicator system_woke \
	\
	--add item package-updates $second_row \
	--set package-updates update_freq=43200 \
	script="$PLUGIN_DIR/homebrew-package-tracker.sh" \
	--add event homebrew-update \
	--subscribe package-updates homebrew-update \
	\
	--update

#───────────────────────────────────────────────────────────────────────────────

# INFO
# - `--update` needs to run at the end of config and should not be run in an item script
# - `repo-files-update` gets triggered via Hammerspoon path watcher after sync events
# - clock and alias items needs the fixed-width to fix whitespace of the item next (stats)
# - not using builtin clock, to be able to customize font etc.
