#!/usr/bin/env bash
export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH

usage="Usage: $(basename "$0") [-h | --help] <cmd>

Returns the positional command line arguments for <cmd>. Only long (--arg)
optional arguments are supported.

The regex used to extract the options can be overridden by setting the 
CLI_OPTIONS_REGEX environment variable.

where:
    options:
    -h --help   shows this help messages

    positional:
    <cmd>   an existing command"

options=$(getopt -o h --long help -- "$@")

[ $? -eq 0 ] || { echo "Incorrect options provided"; exit 1; }

eval set -- "$options"
while true; do
    case "$1" in
    -h | --help)
        echo "$usage"
        exit
        ;;
    --)
        shift
        break
        ;;
    esac
    shift
done

[ $# -eq 0 ] && { echo "$usage"; exit ;}

cmd=$@

[[ -z $CLI_OPTIONS_CMD ]] && CLI_OPTIONS_CMD="$cmd --help" 

if [[ -z $CLI_OPTIONS_REGEX ]]; then
    HEAD='?<=[^''"`]'
    TAIL='?=\s{2,}|(?<=[^\.])\n| <'
    OBLIGATORY_CHARS='--'
    ALLOWED_SYMBOLS='\[\]\-\=\.\,\%'
    ALLOWED_LETTERS_AND_NUMBERS='a-zA-Z0-9'

    re="($HEAD)"
    re+="($OBLIGATORY_CHARS)"
    re+="([$ALLOWED_LETTERS_AND_NUMBERS]+"
    re+="[$ALLOWED_LETTERS_AND_NUMBERS$ALLOWED_SYMBOLS]*)"
    re+="($TAIL)"
    
    CLI_OPTIONS_REGEX=$re
fi

eval $CLI_OPTIONS_CMD | ag --only-matching --numbers -- "$CLI_OPTIONS_REGEX"
