set quiet

test_vault := "$HOME/writing-vault/"
plugin_name := "time-tracking-helper"

#───────────────────────────────────────────────────────────────────────────────

[macos]
build-and-reload:
    #!/usr/bin/env zsh
    if [[ ! -d "{{ test_vault }}/.obsidian" ]]; then
        echo
        echo "Vault not found: {{ test_vault }}/.obsidian"
        return 1
    fi
    plugin_id=$(grep '"id"' "./manifest.json" | cut -d'"' -f4)
    mkdir -p "{{ test_vault }}/.obsidian/plugins/$plugin_id/"
    cp -f "manifest.json" "main.js" "{{ test_vault }}/.obsidian/plugins/$plugin_id/"

    vault_name=$(basename "{{ test_vault }}")
    open "obsidian://open?vault=$vault_name"

    # reload (REQUIRES: registering the URI manually in a helper plugin)
    open "obsidian://reload-plugin?id=$plugin_id&vault=$vault_name"

[macos]
zip:
    #!/usr/bin/env zsh
    zip --recurse-paths "../{{ plugin_name }}.zip" ./
    open -R "../{{ plugin_name }}.zip"
