set quiet := true

#───────────────────────────────────────────────────────────────────────────────

[macos]
build-and-reload:
    #!/usr/bin/env zsh
    plugin_id=$(grep '"id"' "./manifest.json" | cut -d'"' -f4)
    open "obsidian://reload-plugin?id=$plugin_id"

zip:
    #!/usr/bin/env zsh
    name="time-tracking-helper"
    rm "$name.zip"
    mkdir "$name"
    cp ./* "./$name/"
    zip -r "/tmp/$name.zip" "./$name" >/dev/null
    rm -rf "./$name"
    open -R "/tmp/$name.zip"
