set quiet := true

debugFile := "./debug/test.ts"
debugConfig := "./debug/repro.lua"
masonPath := "$HOME/.local/share/nvim/mason/bin/"

#───────────────────────────────────────────────────────────────────────────────

count-lines:
    #!/usr/bin/env zsh
    find -E . -iregex ".*\.(lua|scm)$" \
        -not -path "./debug/*" -not -path "./templates/*" -print0 |
        xargs -0 wc -l |
        sort --reverse |
        cut -c5- |
        sed 's|\./||'

# runs minimal config with neovide
debug-instance:
    neovide --no-tabs {{ debugFile }} -- -u {{ debugConfig }} &>/dev/null

stylua-on-all:
    #!/usr/bin/env zsh
    {{ masonPath }}/stylua --check --output-format=summary . && return 0
    {{ masonPath }}/stylua .
    echo "\nFiles formatted."
