# yaml-language-server: $schema=https://json.schemastore.org/stylelintrc.json
# explicitly setting schema since using non-standard filename
#───────────────────────────────────────────────────────────────────────────────
# DOCS https://stylelint.io/user-guide/rules
#───────────────────────────────────────────────────────────────────────────────
reportInvalidScopeDisables: true
reportNeedlessDisables: true
#───────────────────────────────────────────────────────────────────────────────
# INFO auto-fixed rules are declared as warnings, so they are not displayed in
# the editor due to `--quiet`
defaultSeverity: warning
#───────────────────────────────────────────────────────────────────────────────
rules:
  color-function-notation: [modern, { ignore: [with-var-inside] }]
  color-named: never
  color-no-hex: true
  comment-empty-line-before: null
  selector-class-pattern: null # class names usually not defined by me
  selector-id-pattern: null # id names usually not defined by me
  no-descending-specificity: null
  custom-property-empty-line-before: never
  declaration-empty-line-before: never
  declaration-no-important: true
  font-weight-notation: numeric
  hue-degree-notation: number # compatible with ccc.nvim output
  max-nesting-depth: 3
  selector-nested-pattern:
    ["&", { splitList: true, message: "Nested selectors should include a &." }]
