---
name: pylyzer_alt
description: A fast static code analyzer & language server for Python.
homepage: https://github.com/mtshiba/pylyzer
licenses:
  - MIT
languages:
  - Python
categories:
  - LSP

source:
  id: pkg:github/mtshiba/pylyzer@v0.0.51
  asset:
    - target: darwin_arm64
      file: pylyzer-aarch64-apple-darwin.tar.gz
    - target: darwin_x64
      file: pylyzer-x86_64-apple-darwin.tar.gz

bin:
  pylyzer: pylyzer
