# yaml-language-server: $schema=https://github.com/mason-org/registry-schema/releases/latest/download/package.schema.json
---
name: just-lsp
description: just-lsp is a server implementation of the language server protocol for just, the command runner.
homepage: https://github.com/terror/just-lsp/releases
licenses:
  - CC0-1.0
languages:
  - Just
categories:
  - LSP

source:
  id: pkg:github/terror/just-lsp@0.1.3
  asset:
    - target: darwin_arm64
      file: actionlint_{{ version | strip_prefix "v" }}_darwin_amd64.tar.gz
      bin: actionlint
    - target: darwin_arm64
      file: actionlint_{{ version | strip_prefix "v" }}_darwin_arm64.tar.gz
      bin: actionlint
    - target: linux_x64
      file: actionlint_{{ version | strip_prefix "v" }}_linux_amd64.tar.gz
      bin: actionlint
    - target: linux_arm64
      file: actionlint_{{ version | strip_prefix "v" }}_linux_arm64.tar.gz
      bin: actionlint
    - target: linux_arm
      file: actionlint_{{ version | strip_prefix "v" }}_linux_armv6.tar.gz
      bin: actionlint
    - target: linux_x86
      file: actionlint_{{ version | strip_prefix "v" }}_linux_386.tar.gz
      bin: actionlint
    - target: win_x64
      file: actionlint_{{ version | strip_prefix "v" }}_windows_amd64.zip
      bin: actionlint.exe
    - target: win_arm64
      file: actionlint_{{ version | strip_prefix "v" }}_windows_arm64.zip
      bin: actionlint.exe
    - target: win_x86
      file: actionlint_{{ version | strip_prefix "v" }}_windows_386.zip
      bin: actionlint.exe

bin:
  actionlint: "{{source.asset.bin}}"
