# https://atuin.sh/docs/config/
#───────────────────────────────────────────────────────────────────────────────

db_path = "$DATA_DIR/atuin/history.db"

## possible values: prefix, fulltext, fuzzy, skim
# search_mode = "fuzzy"

## which filter mode to use
## possible values: global, host, session, directory
filter_mode = "session"

## possible values: auto, full, compact
# style = "auto"
# show_preview = true
inline_height = 15

## what to do when the escape key is pressed when searching
## possible values: return-original, return-query
# exit_mode = "return-original"

## number of context lines to show when scrolling by pages
scroll_context_lines = 3

## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
history_filter = [
	"^inspect$",
]
