# https://prettier.io/docs/en/options.html
printWidth: 100
tabWidth: 3
useTabs: true
bracketSpacing: true
arrowParens: avoid
trailingComma: all
quoteProps: consistent

# filetype-spefic overrides
overrides:
  - files: ["*.yaml", "*.yml", "*.json"]
    options:
      tabWidth: 2
      useTabs: false
      printWidth: 120
