# https://yamllint.readthedocs.io/en/stable/configuration.html#extending-the-default-configuration
extends: default

yaml-files:
  - "*.yaml"
  - "*.yml"

rules:
  line-length: disable
  document-start: disable
  trailing-spaces: disable
  braces: disable
  new-line-at-end-of-file: disable
  comments:
    min-spaces-from-content: 1
    require-starting-space: false
  empty-lines: { level: warning }
  brackets: { level: warning }
