# https://github.com/lukas-reineke/cbfmt#config
# INFO: "Each format command needs to read from stdin and write to stdout."
#───────────────────────────────────────────────────────────────────────────────

# Naming config files necessary: https://github.com/lukas-reineke/cbfmt/issues/35

[languages]
# lua = ["stylua --config-path=/Users/chrisgrieser/.config/linter-configs/stylua.toml -"]
lua = ["stylua -s -"]
python = ["black --fast -"]
yaml = ["prettier --parser=yaml --config=/Users/chrisgrieser/.config/linter-configs/prettierrc.yml"]
json = ["prettier --parser=json --config=/Users/chrisgrieser/.config/linter-configs/prettierrc.yml"]
javascript = ["prettier --parser=babel --config=/Users/chrisgrieser/.config/linter-configs/prettierrc.yml"]
typescript = ["prettier --parser=typescript --config=/Users/chrisgrieser/.config/linter-configs/prettierrc.yml"]
html = ["prettier --parser=html --config=/Users/chrisgrieser/.config/linter-configs/prettierrc.yml"]
bash = ["shfmt -"]
zsh = ["shfmt -"]
sh = ["shfmt -"]
css = ["stylelint --fix --config=/Users/chrisgrieser/.config/linter-configs/stylelintrc-formatting.yml"]
markdown = ["markdownlint --stdin --fix --config=/Users/chrisgrieser/.config/linter-configs/markdownlintrc"]
