# https://github.com/lukas-reineke/cbfmt#config
# INFO: "Each format command needs to read from stdin and write to stdout."
#───────────────────────────────────────────────────────────────────────────────

# Naming config files necessary: https://github.com/lukas-reineke/cbfmt/issues/35

[languages]
lua = ["stylua --config-path=/Users/chrisgrieser/.config/linter-configs/stylua.toml -"]
python = ["black --fast -"]
yaml = ["prettier --config=/Users/chrisgrieser/.config/linter-configs/prettierrc.yml"]
json = ["prettier --config=/Users/chrisgrieser/.config/linter-configs/prettierrc.yml"]
javascript = ["prettier --config=/Users/chrisgrieser/.config/linter-configs/prettierrc.yml"]
typescript = ["prettier --config=/Users/chrisgrieser/.config/linter-configs/prettierrc.yml"]
bash = ["shfmt -"]
zsh = ["shfmt -"]
sh = ["shfmt -"]
css = ["stylelint --fix --config=/Users/chrisgrieser/.config/linter-configs/stylelintrc-formatting.yml"]
markdown = ["markdownlint --stdin --fix --config=/Users/chrisgrieser/.config/linter-configs/markdownlintrc"]
