# DOCS https://github.com/philocalyst/infat#4-configuration

[extensions]
txt = "TextEdit"
pdf = "Highlights"
ics = "Calendar"
svg = "neovide"
url = "Brave Browser" # link files
webloc = "Brave Browser" # link files
md = "Obsidian Helper"
html = "Brave Browser"

[schemes]
mailto = "Mimestream"
web = "Brave Browser"
magnet = "Transmission"

[types] # fallbacks
plain-text = "neovide"
video = "IINA"
movie = "IINA"
mp4-movie = "IINA"
archive = "Archive Utility"
