# DOCS https://github.com/philocalyst/infat#4-configuration
# Apps outside of `/Applications/` require an absolute path or path relative to
# the home directory https://github.com/philocalyst/infat/blob/main/README.md#5-configuration

[extensions]
txt = "TextEdit"
pdf = "Highlights"
ics = "Calendar"
svg = "neovide"
url = "Brave Browser"    # link files
webloc = "Brave Browser" # link files
md = "../../obsidian/opener/Obsidian Helper.app"
html = "Brave Browser"

[schemes]
mailto = "Mimestream"
web = "Brave Browser"
magnet = "Transmission"

[types] # fallbacks
plain-text = "neovide"
video = "IINA"
movie = "IINA"
mp4-movie = "IINA"
archive = "/System/Library/CoreServices/Applications/Archive Utility.app"
