#!/usr/bin/env zsh

# CONFIG
username="pseudometa"
bkp_destination="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Backups/watchlists/"

#───────────────────────────────────────────────────────────────────────────────

clone_and_venv() {
	cd /tmp/ || return 1
	git clone --no-progress --depth=2 "$1"

	exporter_dir="$(basename "$1" .git)"
	cd "$exporter_dir" || return 1

	[[ -d ./.venv ]] && rm -rf ./.venv
	python3 -m venv ./.venv
	# shellcheck disable=1091
	source ./.venv/bin/activate
	python3 -m pip install --quiet -r requirements.txt
}

#───────────────────────────────────────────────────────────────────────────────

exporter_mal_xml="https://github.com/Jacekun/AniPy"
clone_and_venv "$exporter_mal_xml"

# sending empty line to stdin to skip "press enter to exit" prompt at the end
echo | python3 anipy.py -user="$username"

cp -f ./output/anime*.json "$bkp_destination/anilist_$(date +%Y-%m-%d).json"
rm -rf /tmp/"$(basename "$exporter_mal_xml")"

open "$bkp_destination"

#───────────────────────────────────────────────────────────────────────────────
# ALTERNATIVE 
# less pretty data, mostly intended for import to MAL

# exporter_mal_xml="https://github.com/staticaron/AnilistToMalExporter"
# clone_and_venv "$exporter_mal_xml"
# python3 convertor.py "$username" > "anilist-plain.txt"
# cp -vf ./*.{xml,txt} "$bkp_destination"
