#!/usr/bin/env zsh
echo "Checking for command line tools updates…"

update=$(softwareupdate --list |
	grep --only-matching --extended-regexp 'Command Line Tools.*$' |
	head -n1)

if [[ -z "$update" ]]; then
	echo "No update for command line tools available."
else
	softwareupdate --install "$update"
	
	osascript -e 'display notification "Update finished." with title "🖥️ Command Line Tools" sound name "Blow"'
fi
