#!/usr/bin/env zsh

# CONFIG
github_username="chrisgrieser"
download_location="$HOME/Developer/"


# repo_names="alfred|shimmering-obsidian|gitfred"
repo_names="nvim"
# repo_names="obsidian-quadro|pseudometa-obsidian-plugin-template|grappling-hook|obsidian-proofreader"
# ALL
# repo_names="finder-vim-mode|zsh-magic-dashboard|nvim|alfred|shimmering-obsidian|gitfred|obsidian-quadro|pseudometa-obsidian-plugin-template|grappling-hook"

#───────────────────────────────────────────────────────────────────────────────
#───────────────────────────────────────────────────────────────────────────────

# GUARD
if [[ ! -x "$(command -v gh)" ]]; then print "\e[1;33mgh not installed.\e[0m" && return 1; fi

# only non-forked, non-archived repos
repos_to_update=$(gh repo list --limit=100 --no-archived --source --visibility=public \
	--json="name" --jq=".[].name | select(test(\"$repo_names\"))")
repo_count=$(echo "$repos_to_update" | wc -l | tr -d " ")

# confirmation that everything is correct
print "\e[1;34mRepos to download ($repo_count):\e[0m"
echo "$repos_to_update" | rs
echo
print "\e[1;34mDownload location:\e[0m"
echo "$download_location"
echo
print "\e[1;34mProceed? (y/n)\e[0m"
read -r pressed
if [[ "$pressed" != "y" ]]; then
	echo
	echo "Aborted."
	return 1
fi
echo
echo "────────────────────────"
echo

#───────────────────────────────────────────────────────────────────────────────

if [[ -d "$download_location" ]] ; then
	cd "$download_location" || return 1
else
	echo "$download_location does not exist."
	return 1
fi

# clone each repo, do the replacements, and git add/commit/push
while read -r repo; do
	# WARN depth 2 relevant for prevent history loss when amending
	git clone --no-progress --depth=2 "git@github.com:$github_username/$repo"
done <<< "$repos_to_update"

#───────────────────────────────────────────────────────────────────────────────

"$ZDOTDIR/notificator" --title "🌐Multi-repo download" --message "Download finished." --sound "Blow"
