#!/usr/bin/env zsh

# CONFIG
github_username="chrisgrieser"
# set -e

# repo_names="alfred|shimmering-obsidian|gitfred"
repo_names="nvim"
# repo_names="obsidian-quadro|pseudometa-obsidian-plugin-template|grappling-hook|obsidian-proofreader"
# ALL
# repo_names="finder-vim-mode|zsh-magic-dashboard|nvim|alfred|shimmering-obsidian|gitfred|obsidian-quadro|pseudometa-obsidian-plugin-template|grappling-hook|obsidian-proofreader"

function actions_in_repo {
	git reset --hard HEAD^
	git apply "$HOME"/Desktop/patchN
	sed -i '' -e 's/^# Nvim-/# nvim-/' -e '1s/$/ <!-- rumdl-disable-line MD063 `nvim` lowercased -->/' README.md
	rumdl fmt --disable=MD007
}

commit_msg="docs: enforce sentence case headings"

amend_no_edit="true"

#───────────────────────────────────────────────────────────────────────────────
#───────────────────────────────────────────────────────────────────────────────
_export_github_token # defined in .zshenv

# GUARD
if [[ -z "$GITHUB_TOKEN" ]]; then
	print "\e[1;31mNo GitHub token found\e[0m"
	return 1
elif [[ ! -x "$(command -v gh)" ]]; then
	print "\e[1;33mgh not installed.\e[0m"
	return 1
fi

# only non-forked, non-archived repos
repos_to_update=$(gh repo list --limit=100 --no-archived --source --visibility=public \
	--json="name" --jq=".[].name | select(test(\"$repo_names\"))" |
	grep -vE "scissors|rulebook|puppeteer")
repo_count=$(echo "$repos_to_update" | wc -l | tr -d " ")

# confirmation that everything is correct
print "\e[1;34mRepos to update ($repo_count):\e[0m"
echo "$repos_to_update" | rs
echo

if [[ "$amend_no_edit" == "true" ]]; then
	print "\e[0;33mWARN: Amending to previous commit"
else
	print "\e[1;34mCommit message:\e[0m"
	echo "$commit_msg"
fi

echo
print "\e[1;34mActions:\e[0m"
declare -f actions_in_repo | sed '1d;$d;s/^\t//' | bat --language=sh --no-pager
echo
print "\e[1;34mProceed? (y/n)\e[0m"
read -r pressed
[[ "$pressed" != "y" ]] && return 1
echo
echo "────────────────────────"
echo

#───────────────────────────────────────────────────────────────────────────────

cd /tmp || return 1

# clone each repo, do the replacements, and git add/commit/push
i=1
not_updated=0
while read -r repo; do
	print "\e[1;34mUpdating $repo… ($i/$repo_count)\e[0m"
	# WARN depth 5 relevant for prevent history loss when amending (extra safety net)
	git clone --no-progress --depth=5 "git@github.com:$github_username/$repo"
	cd "$repo" || return 1

	actions_in_repo

	# COMMIT/AMEND
	if [[ "$amend_no_edit" == "true" ]]; then
		git add --all &&
			# git commit --amend --message="$commit_msg" &&
			git commit --amend --no-edit &&
			git push --no-progress --force
	else
		git add --all && git commit --message="$commit_msg" && git push --no-progress
	fi

	success=$?
	if [[ $success -ne 0 ]]; then
		print "\e[1;33mDid not update $repo.\e[0m"
		((not_updated++))
	fi

	echo
	cd ..
	rm -rf "$repo"
	((i++))
done <<< "$repos_to_update"

#───────────────────────────────────────────────────────────────────────────────

if [[ $not_updated -gt 0 ]]; then
	echo "────────────────────────"
	print "\e[1;33m$not_updated repo(s) not updated.\e[0m"
fi
"$ZDOTDIR/notificator" --title "🌐Multi-repo commit" --message "Update finished." --sound "Blow"
