#!/usr/bin/env zsh

# REQUIRED Installing the `ntfy` app on the phone and adding the ID there

#-------------------------------------------------------------------------------

# stored outside dotfiles for security
uuid=$(cat "$HOME/Library/Mobile Documents/com~apple~CloudDocs/Tech/api-keys/ntfy-sh-id.txt")
title="$1"
message="$2"
emoji="$3"

if [[ -z "$message" ]] ; then
	message="$title"
	title="Notification from Desktop"
fi

#-------------------------------------------------------------------------------

# DOCS https://docs.ntfy.sh/publish/
curl \
	--header "Title: $title" \
	--data "$message" \
	--header "Tags: $emoji" \
	"ntfy.sh/$uuid" \
	&>/dev/null
