#!/usr/bin/env zsh

filepath="xxx"
original_clone_url="xxx"
#-------------------------------------------------------------------------------
brew install git-filter-repo
git filter-repo --invert-paths --path "$filepath"
git remote add origin "$original_clone_url"
git push --force --all
git push --force --tags
#-------------------------------------------------------------------------------
# brew uninstall git-filter-repo
