# https://osric.com/bingo-card-generator/
Fritz baut etwas stufenlos Höhenverstellbares,
"Zusatzmissionen" wie von Sebo vorhergesagt,
"If it's black: fight back. If it's brown: lay down. If it's white: good night",
Knossi raucht 2 Zigaretten an einem Tag,
Ein Team kuschelt in der Nacht,
Bär wird gesichtet,
RML wird mit der Aufklärung eines Sachverhaltes beauftragt,
Teilnehmer verflucht Max & Johannes,
Knossi & Sascha heulen gemeinsam Mond an,
Ein Team trennt sich (temporär),
Cliffhanger von letzter Folge war ein Bluff,
Ein Team verliert seine Flasche,
Abbruch wegen Hunger,
Affe verwertet ihren Popel/Ohrenschmalz,
Unterwäsche wird zweckentfremdet,
Niklas' Flasche wird thematisiert,
Essen fällt ins Feuer und verbrennt,
Info-Einblendung erklärt dass ein Teilnehmer daneben liegt,
Feuerstahl/Feuerzeug geht verloren (Grüße an Joris),
2 Teilnehmer berichten in einer Folge von ihrem Stuhlgang,
Shoutout an Otto,
"Guten Morgen Andy!" (Gerrit),
Sascha-Vortrag über die Biologie des Bären,
Knossi hat einen BH mitgebracht oder bastelt sich einen vor Ort,
Rumathras Kupferblech geht kaputt / ist ein Reinfall,
Wissen aus einem Survival-Game ist tatsächlich nützlich,
Thomas Gast macht ein respektvolles & konstruktives Reaction-Video,
Fisch wird mit einer anderen Methode als Angeln gefangen,
Ein Profi-Teams scheidet vor den 14 Tagen aus,
"Wenn ihr sehen wollt wie … dann bleibt dabei!" (Naturensöhne),
Papaplatte und Reze benutzen eine ganze Folge lang kein Englisch,
Fehlende Messerscheide wird zum Verhängnis,
"Hyped – Bock – Angriff",
"XYZ hat alles falsch gemacht" (Joe Vogel),
Insekten als Nahrungsquelle,
Streamer spricht Publikum als "Chat" an,
