#!/usr/bin/env zsh
# vim: filetype=bash

# CONFIG
max_file_size_mb=10

#───────────────────────────────────────────────────────────────────────────────

# safeguard against accidental pushing of large files
large_files=$(find . -not -path "**/.git/**" -size +${max_file_size_mb}M)
if [[ -n "$large_files" ]]; then
	print "\033[1;33m"
	echo "$large_files"
	echo
	print "Large file(s) found. Aborting commit.\033[0m"
	exit 1
fi
