#!/usr/bin/env zsh
# vim: filetype=bash

# CONFIG
max_file_size_mb=10

#───────────────────────────────────────────────────────────────────────────────

# safeguard against accidental pushing of large files
number_large_files=$(find . -not -path "**/.git/**" -size +${max_file_size_mb}M | wc -l | xargs)
if [[ $number_large_files -gt 0 ]]; then
	print "\033[1;33m$number_large_files large files found. Aborting commit.\033[0m"
	exit 1
fi

exit 0
