# https://github.com/lukas-reineke/cbfmt#config
# INFO: "Each format command needs to read from stdin and write to stdout."
#───────────────────────────────────────────────────────────────────────────────

# Naming config files necessary: https://github.com/lukas-reineke/cbfmt/issues/35

[languages]
lua = ["stylua --config-path=/Users/chrisgrieser/.config/_linter-configs/stylua.toml -"]
python = ["black --fast -"]
json = ["yq -o=json"]
yaml = ["yq --prettyPrint"]
bash = ["shfmt -"]
zsh = ["shfmt -"]
sh = ["shfmt -"]
css = ["stylelint --fix --config=/Users/chrisgrieser/.config/_linter-configs/stylelintrc-formatting.yml"]
markdown = ["markdownlint --stdin --fix --config=/Users/chrisgrieser/.config/_linter-configs/markdownlintrc"]
