# DOCS https://github.com/codespell-project/codespell#using-a-config-file
#───────────────────────────────────────────────────────────────────────────────

[tool.codespell]
# SIC needs to be empty string instead of `true`
check-hidden = ""
builtin = "rare,clear,informal,code,names,usage,en-GB_to_en-US"

# IGNORE

# needs ** to match independent of pwd
# needs * to match conform.nvim's temporary files
skip = """\
**/*main-bibliography.bib,\
**/*spelling.yml,\
**/*abbreviations.lua,\
"""

ignore-regex = "base64,\\S{500,}" # ignore base64-encoded content, e.g. in css files

uri-ignore-words-list = "*" # ignore all misspellings in URLs/mail-adresses

ignore-words-list = """\
noice,\
acknowledgements,aesthetics,\
"""
