# DOCS https://github.com/codespell-project/codespell#using-a-config-file
#───────────────────────────────────────────────────────────────────────────────

[tool.codespell]
# SIC needs to be empty string instead of `true`
check-hidden = ""
builtin = "rare,clear,informal,code,names,usage,en-GB_to_en-US"

#───────────────────────────────────────────────────────────────────────────────

# IGNORE

# needs ** to match independent of pwd
# needs * to match conform.nvim's temporary files
skip = """\
**/*main-bibliography.bib,\
**/*spelling.yml,\
**/*abbreviations.lua,\
"""

# ignore base64-encoded content, e.g. in css files
# ignore lines ending with "codespell-ignore" https://github.com/codespell-project/codespell/issues/1212#issuecomment-1721152455
ignore-regex = "base64,\\S{500,}|.*codespell-ignore$"

uri-ignore-words-list = "*" # ignore all misspellings in URLs/mail-adresses

ignore-words-list = """\
noice,acknowledgements,aesthetics,bu,\
master,\
"""
