# DOCS https://microsoft.github.io/pyright/#/configuration?id=type-check-diagnostics-settings
[tool.pyright]
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
typeCheckingMode = "basic"
useLibraryCodeForTypes = true

#───────────────────────────────────────────────────────────────────────────────

# DOCS https://beta.ruff.rs/docs/rules/
[tool.ruff]
line-length = 100
select = ["ALL"]
ignore = [
	"T201",   # print statements
	"S311",   # requires cryptographically secure random number generators
	"W",      # pycodestyle warnings are already autofixed by black
	"RET504", # unnecessary assign for return (makes stuff less verbose)
	"ERA001", # commented out code
	"TD",     # allow TODO
	"FIX002", # complain about TODO in general
	"FIX004", # complain about HACK
	"S607",   # shell command without full path
	"S605",   # shell instead of subshell

	# DUPLICATON WITH PYRIGHT
	"F841",   # unused var
	"F401",   # unused import
	"ARG001", # unused arg
	"F821",   # undefined variable
]

[tool.ruff.pydocstyle]
convention = "google" # "google"|"numpy"|"pep257"

#───────────────────────────────────────────────────────────────────────────────

[tool.pylint."MESSAGES CONTROL"]
enable = ["useless-suppression"]
disable = [
	"fixme",        # allow TODO
	"import-error",

	# DUPLICATON WITH PYRIGHT/RUFF
	"too-many-locals",
	"unused-variable",
	"undefined-variable",
	"unused-argument",
	"unused-import",
	"trailing-newlines",   # taken care of by formatter
	"trailing-whitespace", # taken care of by formatter
]
