# DOCS https://beta.ruff.rs/docs/rules/
#───────────────────────────────────────────────────────────────────────────────

[tool.ruff]
select = [ "ALL" ]
ignore = []

[tool.ruff.pydocstyle]
convention = "google"  # Accepts: "google", "numpy", or "pep257".
