# DOCS https://beta.ruff.rs/docs/rules/
#───────────────────────────────────────────────────────────────────────────────

[tool.ruff]
select = [ "ALL" ]
ignore = [
	"T201", # print statements
	"S311", # requires cryptographically secure random number generators
	"W", # pycodestyle warnings which are autofixed by black anyway
]

[tool.ruff.pydocstyle]
convention = "pep257"  # Accepts: "google", "numpy", or "pep257".
