# DOCS https://github.com/crate-ci/typos/blob/master/docs/reference.md
# INFO LSP does not support all fields yet: https://github.com/tekumara/typos-vscode#config-file-supportv
#───────────────────────────────────────────────────────────────────────────────

[default.extend-words]
# ignore these words
noice = "noice"
Termine = "Termine"
als = "als"
Fixe = "Fixe" # no inline ignore yet
ue = "ue" # no inline ignoring yet https://github.com/crate-ci/typos/pull/695

# ignore these files
[files]
extend-exclude = [
	"main-bibliography.bib", # too many false positives, PENDING https://github.com/crate-ci/typos/issues/316
	"spelling.yml",          # spell fixer
	"abbreviations.lua",     # spell fixer
]
