#!/usr/bin/env zsh

# CONFIG
python="python3.12"
username="pseudometa"
backupdir="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Backups/anilist/"

#───────────────────────────────────────────────────────────────────────────────

clone_and_venv() {
	cd /tmp/ || return 1
	git clone --depth=2 "$1"

	exporter_dir="$(basename "$1" .git)"
	cd "$exporter_dir" || return 1
	[[ -d ./.venv ]] && rm -rf ./.venv

	"$python" -m venv ./.venv
	# shellcheck disable=1091
	source ./.venv/bin/activate
	# shellcheck disable=2016
	py_path="$(command which python3 | sed 's|^$HOME/|~/|')"
	print "Now using: \e[1;36m$py_path\e[0m"

	python3 -m pip install -r requirements.txt
}

#───────────────────────────────────────────────────────────────────────────────

exporter_json="https://github.com/Jacekun/AniPy"
clone_and_venv "$exporter_json"
python3 anipy.py -user "$username" # AniPy
cp -vf ./output/anime_*.json "$backupdir"

echo "----------"

exporter_mal_xml="https://github.com/staticaron/AnilistToMalExporter"
clone_and_venv "$exporter_mal_xml"
python3 convertor.py "$username"
cp -vf ./*.xml "$backupdir"

open "$backupdir"
