#!/usr/bin/env zsh

# CONFIG
# set -e
github_username="chrisgrieser"

repo_names="alfred|shimmering-obsidian|gitfred"
# repo_names="nvim"
# repo_names="obsidian-quadro|pseudometa-obsidian-plugin-template|grappling-hook"
# repo_names="." # all repos

function actions_in_repo {
	command cp -fv "$HOME/Desktop/.markdownlint.yaml" .
	command cp -fv "$HOME/Desktop/.rsync-exclude" .
}

commit_msg="chore: add markdownlint config"

#───────────────────────────────────────────────────────────────────────────────

# GUARD
if [[ ! -x "$(command -v gh)" ]]; then print "\e[1;33mgh not installed.\e[0m" && return 1; fi

# only non-forked, non-archived repos
repos_to_update=$(gh repo list --limit=100 --no-archived --source --json="name" \
	--jq=".[].name | select(test(\"$repo_names\"))")
repo_count=$(echo "$repos_to_update" | wc -l | tr -d " ")

# confirmation that everything is correct
print "\e[1;34mRepos to update ($repo_count):\e[0m"
echo "$repos_to_update"
echo
print "\e[1;34mCommit message:\e[0m"
echo "$commit_msg"
echo
print "\e[1;34mActions:\e[0m"
declare -f actions_in_repo | sed '1d;$d;s/^\t//' | bat --language=sh
echo
print "\e[1;34mProceed? (y/n)\e[0m"
read -rk pressed
if [[ "$pressed" != "y" ]]; then
	echo
	echo "Aborted."
	return 1
fi
echo && echo

# goto work location
cd /tmp || return 1

#───────────────────────────────────────────────────────────────────────────────
# clone each repo, do the replacements, and git add/commit/push
i=1
not_updated=0
while read -r repo; do
	print "\e[1;34mUpdating $repo… ($i/$repo_count)\e[0m"
	git clone --no-progress --depth=2 "git@github.com:$github_username/$repo"
	cd "$repo" || return 1

	actions_in_repo

	git add --all && git commit -m "$commit_msg" && git push --no-progress
	success=$?
	if [[ $success -ne 0 ]]; then
		print "\e[1;33mDid not update $repo.\e[0m"
		((not_updated++))
	fi

	echo
	cd ..
	rm -rf "$repo"
	((i++))
done <<< "$repos_to_update"

#───────────────────────────────────────────────────────────────────────────────

[[ $not_updated -gt 0 ]] && print "\e[1;33m$not_updated repos not updated.\e[0m"
"$ZDOTDIR/notificator" --title "🌐Multi-repo update" --message "Update finished." --sound "Blow"
