set quiet

karabiner_profile := "Default"

#───────────────────────────────────────────────────────────────────────────────

[macos]
reload:
    osascript -l JavaScript ./build-karabiner-config.js "{{ karabiner_profile }}"

[macos]
browse-docs:
    open "https://karabiner-elements.pqrs.org/docs/"

[macos]
keyboard-layout-editor:
    open -R "./assets/finder-vim-mode/cheatsheet.json"
    open "http://www.keyboard-layout-editor.com/#/"
