set quiet := true

karabiner_profile := "Default"

reload_karabiner:
    osascript -l JavaScript ./build-karabiner-config.js "{{ karabiner_profile }}"

browse_docs:
    open "https://karabiner-elements.pqrs.org/docs/"

keyboard_layout_editor:
    open "http://www.keyboard-layout-editor.com/#/"
