matches:
  - trigger: "... "
    replace: "… "
  - trigger: "::"
    replace: ":innen"
  #─────────────────────────────────────────────────────────────────────────────
  - trigger: "!null"
    replace: "&>/dev/null;"
  #─────────────────────────────────────────────────────────────────────────────
  - trigger: "!web"
    replace: https://chris-grieser.de/
  - trigger: "!twitter"
    replace: https://twitter.com/pseudo_meta
  - trigger: "!github"
    replace: https://github.com/chrisgrieser
  - triggers: ["!blog", "!vim"]
    replace: https://nanotipsforvim.prose.sh
  - trigger: "!paypal"
    replace: https://www.paypal.me/ChrisGrieser
  - trigger: "!name"
    replace: Christopher Grieser
  #─────────────────────────────────────────────────────────────────────────────
  - trigger: "!wd"
    replace: "~/Library/Mobile Documents/com~apple~CloudDocs/File Hub/"
  - trigger: "!path"
    replace: "export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH"
  - triggers: ["!debugger", "!dev"]
    replace: "setTimeout(() => { debugger }, 4000);"
    label: for pasting in the dev tools
  - triggers: ["!selector", "!dev"]
    replace: document.querySelector("$|$")
    label: for pasting in the dev tools
    #───────────────────────────────────────────────────────────────────────────
  - trigger: "!dontask"
    replace: "<https://dontasktoask.com/>"
  - trigger: "!bug"
    replace: Could you open a bug report at the GitHub repo? Reason being that the bug report forms asks for various information I need to investigate the issue. (also, I don't have the time to look into it right now, so an issue will make sure that I can keep track of it.)
    #───────────────────────────────────────────────────────────────────────────
  - trigger: "!iso"
    replace: "{{todayISO}}"
    vars:
      - name: todayISO
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "!today"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%d.%m.%Y"
  - trigger: "!la"
    replace: ", last accessed: {{today}}"
    label: Last Accessed
    vars:
      - name: today
        type: date
        params:
          format: "%d.%m.%Y"
  #─────────────────────────────────────────────────────────────────────────────
  - trigger: "!version"
    replace: "macOS {{version}} (M1)"
    vars:
      - name: version
        type: shell
        params:
          cmd: "sw_vers -productVersion"
  - trigger: "!nversion"
    replace: |
      ```
      macOS {{OSversion}} (M1)
      neovim {{neovimVersion}} (homebrew)
      Neovide {{neovideVersion}} (homebrew)
      ```
    vars:
      - name: OSversion
        type: shell
        params:
          cmd: "sw_vers -productVersion"
      - name: neovimVersion
        type: shell
        params:
          cmd: "export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH ; nvim --version | head -n1 | cut -dv -f2"
      - name: neovideVersion
        type: shell
        params:
          cmd: "export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH ; neovide --version | cut -d' ' -f2"
  - trigger: "!oversion"
    replace: |
      ```
      macOS {{OSversion}} (M1)
      Obsidian {{obsiVersion}}
      ```
    vars:
      - name: OSversion
        type: shell
        params:
          cmd: "sw_vers -productVersion"
      - name: obsiVersion
        type: shell
        params:
          cmd: 'ls ~"/Library/Application Support/obsidian/"*".asar" | xargs -I {} basename {} | cut -d"." -f1-3 | cut -d"-" -f2'
  - trigger: "!resolution"
    replace: "{{resolution}}"
    vars:
      - name: resolution
        type: shell
        params:
          cmd: 'osascript -e ''tell application "Finder" to get bounds of window of desktop'' | cut -d '' '' -f 3,4'
  #─────────────────────────────────────────────────────────────────────
  - trigger: "!lorem"
    replace: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur a cursus sapien. Aenean sed mollis mauris. Morbi hendrerit eros id tortor facilisis, at consectetur dui iaculis. Nullam pharetra felis sit amet velit porttitor placerat. In vel lectus ipsum. Aliquam vestibulum a erat et sollicitudin. Quisque volutpat odio finibus nisi pellentesque, a efficitur lorem aliquam. Nunc tellus est, lacinia at mattis sed, vulputate sed neque. \n\nEtiam mattis neque quis gravida scelerisque. Sed dictum risus ut lacus aliquam suscipit. Nulla facilisi. Duis sed dolor sagittis, laoreet massa nec, semper lorem. Quisque dictum eleifend condimentum. In condimentum eleifend justo a dapibus. Sed dignissim nibh pharetra tortor malesuada, nec dapibus erat viverra. Cras iaculis dignissim libero, et lobortis nisl.\n\nUt id nibh lacinia tortor aliquam porttitor. Donec blandit erat vitae ex vestibulum interdum. Curabitur molestie finibus purus nec finibus. Name vel turpis vitae metus viverra lobortis non eget ante. Pellentesque efficitur fringilla ex. Maecenas consectetur luctus lectus. Donec et gravida purus, vitae efficitur justo.\n\nMorbi vitae ligula est. Fusce eleifend blandit convallis. Etiam leo massa, fringilla nec imperdiet sit amet, accumsan nec nisi. Suspendisse accumsan id diam et tincidunt. Praesent elementum metus non porttitor dapibus. Curabitur pretium malesuada dolor, tempor mollis lacus hendrerit at. \n\nDonec porta, nibh et placerat bibendum, leo dolor ultrices neque, vel tristique metus mi congue massa. Morbi lobortis placerat tellus, vel fringilla nisi vulputate at. Nulla eu lacinia leo. Curabitur lobortis sed sem quis faucibus. Phasellus efficitur, leo vel blandit luctus, erat ipsum dictum lorem, sed molestie tortor risus ut nunc. Aliquam rhoncus justo eu interdum aliquet."
    label: "Lorem: 5 paragraphes"
