# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
#───────────────────────────────────────────────────────────────────────────────
matches:
  #-EMOJIS & SYMBOLS------------------------------------------------------------
  - { trigger: "->", replace: →, word: true } # unicode arrow
  - { trigger: "<3", replace: "🩶" } # use grey haeart instead of red one
  #-PROFILES--------------------------------------------------------------------
  - { trigger: "!web", replace: https://chris-grieser.de/ }
  - { trigger: "!masto", replace: https://pkm.social/@pseudometa }
  - { trigger: "!name", replace: Christopher Grieser }
  - { trigger: "!paypal", replace: https://www.paypal.com/paypalme/ChrisGrieser }
  #-DATE------------------------------------------------------------------------
  - trigger: "!iso"
    replace: "{{todayISO}}"
    vars:
      - name: todayISO
        type: date
        params: { format: "%Y-%m-%d" }
  - trigger: "!la"
    replace: "(last accessed: {{today}})"
    label: Last Accessed
    vars:
      - name: today
        type: date
        params: { format: "%d. %b %Y" }
  #-VERSION---------------------------------------------------------------------
  - trigger: "!version"
    replace: "macOS {{version}} ({{architecture}})"
    vars:
      - name: version
        type: shell
        params: { cmd: sw_vers -productVersion }
      - name: architecture
        type: shell
        params: { cmd: uname -p }
  - trigger: "!nversion" # typos: ignore-line
    replace: "{{neovimVersion}}"
    vars:
      - name: neovimVersion
        type: shell
        params:
          cmd: |
            export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH 
            nvim --version | head -n1
  #-----------------------------------------------------------------------------

