matches:
  - trigger: "... "
    replace: "… "
  #─────────────────────────────────────────────────────────────────────────────
  - trigger: "!web"
    replace: https://chris-grieser.de/
  - trigger: "!twitter"
    replace: https://twitter.com/pseudo_meta
  - trigger: "!github"
    replace: https://github.com/chrisgrieser
  - triggers: ["!blog", "!vim"]
    replace: https://nanotipsforvim.prose.sh
  - trigger: "!paypal"
    replace: https://www.paypal.me/ChrisGrieser
  - trigger: "!name"
    replace: Christopher Grieser
  #─────────────────────────────────────────────────────────────────────────────
  - trigger: "!wd"
    replace: "~/Library/Mobile Documents/com~apple~CloudDocs/File Hub/"
  - trigger: "!path"
    replace: "export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH"
  - triggers: ["!debugger", "!dev"]
    replace: "setTimeout(() => { debugger }, 4000);"
    label: for pasting in the dev tools
  - triggers: ["!selector", "!dev"]
    replace: document.querySelector("$|$")
    label: for pasting in the dev tools
  - trigger: "!null"
    replace: "&>/dev/null;"
    #───────────────────────────────────────────────────────────────────────────
  - trigger: "!dontask"
    replace: "<https://dontasktoask.com/>"
  - trigger: "!bug"
    replace: Could you open a bug report at the GitHub repo? Reason being that the bug report forms asks for various information I need to investigate the issue. (also, I don't have the time to look into it right now, so an issue will make sure that I can keep track of it.)
    #───────────────────────────────────────────────────────────────────────────
  - trigger: "!iso"
    replace: "{{todayISO}}"
    vars:
      - name: todayISO
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "!today"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%d.%m.%Y"
  - trigger: "!la"
    replace: ", last accessed: {{today}}"
    label: Last Accessed
    vars:
      - name: today
        type: date
        params:
          format: "%d.%m.%Y"
  #─────────────────────────────────────────────────────────────────────────────
  - trigger: "!version"
    replace: "macOS {{version}} (M1)"
    vars:
      - name: version
        type: shell
        params:
          cmd: "sw_vers -productVersion"
  - trigger: "!nversion"
    replace: |
      ```
      macOS {{OSversion}} (M1)
      neovim {{neovimVersion}} (homebrew)
      Neovide {{neovideVersion}} (homebrew)
      ```
    vars:
      - name: OSversion
        type: shell
        params:
          cmd: "sw_vers -productVersion"
      - name: neovimVersion
        type: shell
        params:
          cmd: "export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH ; nvim --version | head -n1 | cut -dv -f2"
      - name: neovideVersion
        type: shell
        params:
          cmd: "export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH ; neovide --version | cut -d' ' -f2"
  - trigger: "!oversion"
    replace: |
      ```
      macOS {{OSversion}} (M1)
      Obsidian {{obsiVersion}}
      ```
    vars:
      - name: OSversion
        type: shell
        params:
          cmd: "sw_vers -productVersion"
      - name: obsiVersion
        type: shell
        params:
          cmd: 'ls ~"/Library/Application Support/obsidian/"*".asar" | xargs -I {} basename {} | cut -d"." -f1-3 | cut -d"-" -f2'
  - trigger: "!resolution"
    replace: "{{resolution}}"
    vars:
      - name: resolution
        type: shell
        params:
          cmd: 'osascript -e ''tell application "Finder" to get bounds of window of desktop'' | cut -d '' '' -f 3,4'
