# yaml-language-server: $schema=https://raw.githubusercontent.com/ajmarkow/espanso-schema-json/master/schemas/Espanso_Matches_File_Schema.json
#───────────────────────────────────────────────────────────────────────────────
matches:
  # PROFILES
  - { trigger: "!web", replace: https://chris-grieser.de/ }
  - { trigger: "!masto", replace: https://pkm.social/@pseudometa }
  - { triggers: ["!blog" , "!vim"], replace: https://nanotipsforvim.prose.sh }
  - { trigger: "!name", replace: Christopher Grieser }
  - { trigger: "!paypal", replace: https://www.paypal.com/paypalme/ChrisGrieser }
  #───────────────────────────────────────────────────────────────────────────
  # DATES
  - trigger: "!iso"
    replace: "{{todayISO}}"
    vars:
      - name: todayISO
        type: date
        params: { format: "%Y-%m-%d" }
  - trigger: "!today"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params: { format: "%d. %b. %Y" }
  - trigger: "!la"
    replace: "(last accessed: {{today}})"
    label: Last Accessed
    vars:
      - name: today
        type: date
        params: { format: "%d. %b. %Y" }
  #─────────────────────────────────────────────────────────────────────────────
  - trigger: "!version"
    replace: "macOS {{version}} ({{architecture}})"
    vars:
      - name: version
        type: shell
        params: { cmd: sw_vers -productVersion }
      - name: architecture
        type: shell
        params: { cmd: uname -p }
  #─────────────────────────────────────────────────────────────────────────────
  - trigger: "!github"
    replace: >
      For bug reports, feature requests, or questions about my plugins and workflows, please create
      an issue in the corresponding GitHub repository. This email address is exclusively for
      academic purposes or business inquiries.

      *This is an automated message. Please do not reply to this email.*
