name: Release Alfred Workflow

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "*"

env:
  # Change this to match your workflow name, replacing " " with "-"
  WORKFLOW_NAME: "alfred-atop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log Version
        id: log-version
        run: |
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload .alfredworkflow file
        id: upload-alfredworkflow
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.WORKFLOW_NAME }}.alfredworkflow
          asset_name: ${{ env.WORKFLOW_NAME }}.alfredworkflow
          asset_content_type: application/zip

