set quiet

count-lines:
    #!/usr/bin/env zsh
    find . -type file \( -name "*.zsh" -or -name ".zsh*" \) -not -path "./plugins/*" -print0 |
        xargs -0 wc -l |
        sort --reverse |
        cut -c5- |
        sed 's|\./||'
