set quiet := true

reload:
    #!/usr/bin/env zsh
    open -a "WezTerm"
    pgrep -qx "wezterm-gui" || sleep 0.6
    wezterm cli send-text --no-paste "exec zsh" # do not reload with `source $HOME/.zshrc`, https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-reload-the-zshrc-file

count-lines:
    #!/usr/bin/env zsh
    find . -type file \( -name "*.zsh" -or -name ".zsh*" \) -not -path "./plugins/*" -print0 |
        xargs -0 wc -l |
        sort --reverse |
        cut -c5- |
        sed 's|\./||'
