set quiet := true

# WARN the `^M` breaks the formatting via the just-lsp
#-------------------------------------------------------------------------------


reload:
    #!/usr/bin/env zsh
    if pgrep -qx "wezterm-gui"; then
        # do not reload with `source $HOME/.zshrc`, https://github.com/ohmyzsh/ohmyzsh/wiki/FAQ#how-do-i-reload-the-zshrc-file
        # leading space to not save in in history
        wezterm cli send-text --no-paste " exec zsh"
        open -a "WezTerm" # to focus it
    else
        open -a "WezTerm"
    fi

count-lines:
    #!/usr/bin/env zsh
    find . -type file \( -name "*.zsh" -or -name ".zsh*" \) -not -path "./plugins/*" -print0 |
        xargs -0 wc -l |
        sort --reverse |
        cut -c5- |
        sed 's|\./||'
