set quiet := true

[macos]
reload:
    open -g "hammerspoon://hs-reload"
    echo " Hammerspoon reloaded"

count-lines:
    #!/usr/bin/env zsh
    find . -name "*.lua" -not -path "*/Spoons/*" -print0 |
        xargs -0 wc -l |
        sort --reverse |
        cut -c5- |
        sed 's|\./||'

format-all-lua-files:
    export PATH="$HOME/.local/share/nvim/mason/bin":$PATH
    stylua .
