set quiet := true

# reload Hammerspoon config
[macos]
reload:
    open -g "hammerspoon://hs-reload"
    echo " Hammerspoon reloaded"

# total length of config in LoC
count-lines:
    find . -name "*.lua" -not -path "*/Spoons/*" -print0 | xargs -0 wc -l | sort --reverse
