set quiet := true

masonPath := "$HOME/.local/share/nvim/mason/bin/"

#───────────────────────────────────────────────────────────────────────────────

[macos]
reload:
    open -g "hammerspoon://hs-reload"
    echo " Hammerspoon reloaded"

count-lines:
    #!/usr/bin/env zsh
    find . -name "*.lua" -not -path "*/Spoons/*" -print0 |
        xargs -0 wc -l |
        sort --reverse |
        cut -c5- |
        sed 's|\./||'

stylua-on-all:
    #!/usr/bin/env zsh
    {{ masonPath }}/stylua --check --output-format=summary . && return 0
    {{ masonPath }}/stylua .
    echo "\nFiles formatted."
