---@meta

---@alias WindowEvent
---|"augment-command-palette"
---|"bell"
---|"format-tab-title"
---|"format-window-title"
---|"new-tab-button-click"
---|"open-uri"
---|"update-status"
---|"user-var-changed"
---|"window-config-reloaded"
---|"window-focus-changed"
---|"window-resized"
